def menu():
    print("+---------------------------------------+")
    print("| Welcome to the Python Vending Machine |")
    print("+---------------------------------------+")
    print("|                 Menu                  |")
    print("+---------------------------------------+")
    print("|        1.) KitKat             | $1.50 |")
    print("|        2.) Snickers           | $1.50 |")
    print("|        3.) Dr. Pepper         | $1.00 |")
    print("|        4.) Cheetos            | $1.00 |")
    print("|        5.) Starbursts         | $1.25 |")
    print("+---------------------------------------+")
    print("|            0.) Checkout               |")
    print("+---------------------------------------+")